"""A thin infrastructure layer over BaleClient for personal Bale accounts.

Gives you: one login/session story, an event-driven app runner with reconnect,
one vocabulary for every message kind, and one way to send or download any
attachment. It adds no product behaviour of its own — what a message *means*
is your application's business.
"""

from .patches import apply_wire_fixes

# BaleClient 1.0.9 destroys received text messages during validation; repair
# its models before anything can parse. See bale_userbot/patches.py.
apply_wire_fixes()

from .app import BaleApp, SessionMissingError, prepare_session_file  # noqa: E402
from .client import KitClient  # noqa: E402
from .config import Config  # noqa: E402
from .content import (  # noqa: E402
    MEDIA_KINDS,
    ContactInfo,
    LocationInfo,
    MediaInfo,
    MessageInfo,
    MessageKind,
    QuotedInfo,
    StickerImage,
    StickerInfo,
    describe,
    kind_of_document,
)
from .extras import (  # noqa: E402
    contact_content,
    json_block_content,
    json_content,
    location_content,
    react,
    send_contact,
    send_content,
    send_location,
    send_sticker,
    set_typing,
    sticker_content,
    unreact,
)
from .groups import (  # noqa: E402
    GroupInfo,
    GroupUnavailableError,
    MemberInfo,
    MembershipChanges,
    diff_members,
    export_members,
    fetch_group,
    get_group,
    group_info,
    hydrate_profiles,
    iter_members,
    list_groups,
    load_admins,
    load_members,
    member_count,
    member_info,
    member_records,
    permission_names,
    watch_membership,
)
from .history import (  # noqa: E402
    day_range,
    export_history,
    iter_history,
    load_history,
    message_record,
    message_records,
    to_timestamp,
)
from .limiter import RateLimiter  # noqa: E402
from .media import (  # noqa: E402
    detect_kind,
    download,
    resend,
    send_media,
    suggest_filename,
)
from .moderation import (  # noqa: E402
    PERMISSION_FLAGS,
    InviteLink,
    allow,
    banned,
    demote,
    invite_link,
    join,
    kick,
    leave,
    mute,
    permissions_of,
    pin,
    pins,
    preview,
    promote,
    restrict,
    revoke_invite_link,
    set_default_permissions,
    set_permissions,
    unban,
    unmute,
    unpin,
    unpin_all,
)
from .routing import (  # noqa: E402
    ChatScope,
    FromUsers,
    InChats,
    IsMedia,
    Kind,
    NotSelf,
    wrap_handler,
)
from .store import (  # noqa: E402
    MessageStore,
    SearchHit,
    SearchResult,
    SyncState,
    normalize,
)
from .sync import (  # noqa: E402
    SweepReport,
    SyncReport,
    sync_chat,
    sync_chats,
)

__version__ = "1.0.0"

__all__ = (
    "BaleApp",
    "ChatScope",
    "Config",
    "ContactInfo",
    "FromUsers",
    "GroupInfo",
    "GroupUnavailableError",
    "InChats",
    "InviteLink",
    "IsMedia",
    "Kind",
    "KitClient",
    "LocationInfo",
    "MEDIA_KINDS",
    "MediaInfo",
    "MemberInfo",
    "MembershipChanges",
    "MessageInfo",
    "MessageKind",
    "MessageStore",
    "NotSelf",
    "PERMISSION_FLAGS",
    "QuotedInfo",
    "RateLimiter",
    "SearchHit",
    "SearchResult",
    "SessionMissingError",
    "StickerImage",
    "StickerInfo",
    "SweepReport",
    "SyncReport",
    "SyncState",
    "allow",
    "banned",
    "contact_content",
    "day_range",
    "demote",
    "describe",
    "detect_kind",
    "diff_members",
    "download",
    "export_history",
    "export_members",
    "fetch_group",
    "get_group",
    "group_info",
    "hydrate_profiles",
    "invite_link",
    "iter_history",
    "iter_members",
    "join",
    "json_block_content",
    "json_content",
    "kick",
    "kind_of_document",
    "leave",
    "list_groups",
    "load_admins",
    "load_history",
    "load_members",
    "location_content",
    "member_count",
    "member_info",
    "member_records",
    "message_record",
    "message_records",
    "mute",
    "normalize",
    "permission_names",
    "permissions_of",
    "pin",
    "pins",
    "prepare_session_file",
    "preview",
    "promote",
    "react",
    "resend",
    "restrict",
    "revoke_invite_link",
    "send_contact",
    "send_content",
    "send_location",
    "send_media",
    "send_sticker",
    "set_default_permissions",
    "set_permissions",
    "set_typing",
    "sticker_content",
    "suggest_filename",
    "sync_chat",
    "sync_chats",
    "to_timestamp",
    "unban",
    "unmute",
    "unpin",
    "unpin_all",
    "unreact",
    "watch_membership",
    "wrap_handler",
    "__version__",
)
